name: sonar
on:
    workflow_dispatch:
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name : Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Set up SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
      - name: checkout code
        uses: actions/checkout@v4
     

        #   projectKey: 'SakuraSher_DevSecops_Pipeline'  # Replace with your actual project key
        #   organization: 'sakurasher'  # Replace with your actual organization    
        #   hostUrl: 'https://sonarcloud.io'
      - name: run SonarCloud analysis
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=SakuraSher_DevSecops_Pipeline -Dsonar.organization=sakurasher -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}


