name: sonar
on:
    workflow_dispatch:
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name : Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: build with maven
        run: mvn clean install    
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: '.'          
          args: >
            -Dsonar.projectKey=SakuraSher_DevSecops_Pipeline
            -Dsonar.organization=sakurasher
            -Dsonar.host.url=https://sonarcloud.io/
            
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io/